export enum MenuType {
    WAITERREQUEST ='WAITERREQUEST',
    WAITERCALL ='WAITERCALL',
    SPECIAL ='SPECIAL',
    CHEFCHOICE ='CHEFCHOICE',
    TERMINALREQUEST='TERMINALREQUEST',
    FOOD='FOOD'
}
